handbook:
  labels:
    group: com.stakater.platform
    provider: stakater
    version: 1.0.0    
  service:
    name: "developerhandbook"
    labels:
      expose: 'true'
  deployment:
    tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "app"
      effect: "NoSchedule"
    replicas: 1
    podLabels:      
      app: developer-handbook
    containerName: handbook  
    imagePullSecrets: nexus-secret  
    image:
      name: registry-platform-services.platform.mnscorp.net/kajanth/developer-docs
      tag: 25
      
ingressDomain: perf

ingress:
  ## If true, twistlock Ingress will be created
  ##
  enabled: true

  ## Annotations for Alertmanager Ingress
  ##
  annotations:
    kubernetes.io/ingress.class: nginx

  ## Labels to be added to the Ingress
  ##
  labels: {}

  ## Hostnames.
  ## Must be provided if Ingress is enabled.
  ##
  # NOTE: This just host suffix name. Actual host name in the format - prometheus.<CLUSTER_INGRESS_NAME>.platform.mnscorp.net
  hostsSuffix:
    - platform.mnscorp.net
  # hosts: []
