{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "fullname" . }}
{{- $routePrefix := .Values.routePrefix }}
{{- $ingressDomain := .Values.ingressDomain }}
{{- $ingressHostSuffix := index .Values.ingress.hostsSuffix 0 }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "name" . }}
{{ include "developer-handbook.labels.stakater" . | indent 4 }}
{{ include "developer-handbook.labels.chart" . | indent 4 }}
{{- if .Values.ingress.labels }}
{{ toYaml .Values.ingress.labels | indent 4 }}
{{- end }}
  name: {{ template "fullname" . }}
spec:
  rules:
    - host: developer.{{ $ingressDomain }}.{{ $ingressHostSuffix }}
      http:
        paths:
          - path: "{{ $routePrefix }}"
            backend:
              serviceName: "{{ template "name" . }}"
              servicePort: 8080
{{- end }}
